const Red = 'bf616a' // #bf616a
const Orange = 'd08770' // #d08770
const Yellow = 'ebcb8b' // #ebcb8b
const Green = 'a3be8c' // #a3be8c
const Purple = 'b48ead' // #b48ead
const Gray = '4c566a' // #4c566a

const register = (monaco: any) => {
  monaco.languages.register({id: 'mermaid'})

  monaco.languages.setMonarchTokensProvider('mermaid', {
    // defaultToken: 'invalid',
    keywords: ['graph', 'subgraph', 'end', 'click', 'callback', 'style'],
    configKeywords: ['TB', 'BT', 'RL', 'LR', 'TD'],
    fullConnectors: ['-->', '---'],
    partialConnectors: ['--', '|', '---|'],

    tokenizer: {
      root: [
        [
          /((?:\[|\(|\(\(|>|{)")([^"]*)("(?:]|\)|\)\)|}))/,
          ['bracket', 'label', 'bracket']
        ],
        [
          /(\[|\(|\(\(|>|{)([^)\]}]*)(]|\)|\)\)|})/,
          ['bracket', 'label', 'bracket']
        ],
        [
          /(--|---\||-->\||-\.|==)([a-zA-Z0-9 ]*)(---|\||-->|\.->|==>)/,
          ['connector', 'label', 'connector']
        ],
        [/(-->|---|-\.->|==>)/, 'connector'],
        [
          /[a-zA-Z0-9_$][\w$]*/,
          {
            cases: {
              '@keywords': 'keyword',
              '@configKeywords': 'configKeyword',
              '@default': 'identifier'
            }
          }
        ],
        [/;/, 'line-terminator']
      ]
    }
  })

  monaco.editor.defineTheme('mermaid-theme', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      {token: 'keyword', foreground: Yellow},
      {token: 'configKeyword', foreground: Purple},
      {token: 'connector', foreground: Red},
      {token: 'identifier'},
      {token: 'line-terminator', foreground: Gray},
      {token: 'bracket', foreground: Orange},
      {token: 'label', foreground: Green}
    ],
    colors: {
      focusBorder: '#3b4252',
      foreground: '#d8dee9',
      'activityBar.background': '#2e3440',
      'activityBar.dropBackground': '#3b4252',
      'activityBar.foreground': '#d8dee9',
      'activityBarBadge.background': '#88c0d0',
      'activityBarBadge.foreground': '#2e3440',
      'badge.foreground': '#2e3440',
      'badge.background': '#88c0d0',
      'button.background': '#434c5e',
      'button.foreground': '#d8dee9',
      'button.hoverBackground': '#4c566a',
      'diffEditor.insertedTextBackground': '#a3be8c4d',
      'diffEditor.insertedTextBorder': '#a3be8c4d',
      'diffEditor.removedTextBackground': '#bf616a4d',
      'diffEditor.removedTextBorder': '#bf616a4d',
      'dropdown.background': '#3b4252',
      'dropdown.border': '#3b4252',
      'dropdown.foreground': '#d8dee9',
      'editorCursor.foreground': '#d8dee9',
      'editorIndentGuide.background': '#434c5eb3',
      'editorIndentGuide.activeBackground': '#4c566a',
      'editorLineNumber.foreground': '#d8dee966',
      'editorWhitespace.foreground': '#4c566ab3',
      'editorWidget.background': '#2e3440',
      editorWidgetBorder: '#3b4252',
      'editor.background': '#2e3440',
      'editor.foreground': '#d8dee9',
      'editor.hoverHighlightBackground': '#3b4252',
      'editor.findMatchBackground': '#88c0d066',
      'editor.findMatchHighlightBackground': '#88c0d033',
      'editor.findRangeHighlightBackground': '#88c0d033',
      'editor.lineHighlightBackground': '#434c5e52',
      'editor.lineHighlightBorder': '#434c5e52',
      'editor.inactiveSelectionBackground': '#434c5ecc',
      'editor.selectionBackground': '#434c5ecc',
      'editor.selectionHighlightBackground': '#434c5ecc',
      'editor.rangeHighlightBackground': '#434c5e52',
      'editor.wordHighlightBackground': '#81a1c166',
      'editor.wordHighlightStrongBackground': '#81a1c199',
      'editorError.foreground': '#bf616a',
      'editorError.border': '#bf616a00',
      'editorWarning.foreground': '#ebcb8b',
      'editorWarning.border': '#ebcb8b00',
      'editorBracketMatch.background': '#2e344000',
      'editorBracketMatch.border': '#88c0d0',
      'editorCodeLens.foreground': '#4c566a',
      'editorGroup.background': '#2e3440',
      'editorGroup.border': '#3b425200',
      'editorGroup.dropBackground': '#3b425299',
      'editorGroupHeader.noTabsBackground': '#2e3440',
      'editorGroupHeader.tabsBackground': '#2e3440',
      'editorGroupHeader.tabsBorder': '#3b425200',
      'editorGutter.background': '#2e3440',
      'editorGutter.modifiedBackground': '#ebcb8b',
      'editorGutter.addedBackground': '#a3be8c',
      'editorGutter.deletedBackground': '#bf616a',
      'editorHoverWidget.background': '#3b4252',
      'editorHoverWidget.border': '#3b4252',
      'editorLink.activeForeground': '#88c0d0',
      'editorMarkerNavigation.background': '#5e81acc0',
      'editorMarkerNavigationError.background': '#bf616ac0',
      'editorMarkerNavigationWarning.background': '#ebcb8bc0',
      'editorOverviewRuler.border': '#3b4252',
      'editorOverviewRuler.currentContentForeground': '#3b4252',
      'editorOverviewRuler.incomingContentForeground': '#3b4252',
      'editorOverviewRuler.findMatchForeground': '#88c0d066',
      'editorOverviewRuler.rangeHighlightForeground': '#88c0d066',
      'editorOverviewRuler.selectionHighlightForeground': '#88c0d066',
      'editorOverviewRuler.wordHighlightForeground': '#88c0d066',
      'editorOverviewRuler.wordHighlightStrongForeground': '#88c0d066',
      'editorOverviewRuler.modifiedForeground': '#ebcb8b',
      'editorOverviewRuler.addedForeground': '#a3be8c',
      'editorOverviewRuler.deletedForeground': '#bf616a',
      'editorOverviewRuler.errorForeground': '#bf616a',
      'editorOverviewRuler.warningForeground': '#ebcb8b',
      'editorOverviewRuler.infoForeground': '#81a1c1',
      'editorRuler.foreground': '#434c5e',
      'editorSuggestWidget.background': '#2e3440',
      'editorSuggestWidget.border': '#3b4252',
      'editorSuggestWidget.foreground': '#d8dee9',
      'editorSuggestWidget.highlightForeground': '#88c0d0',
      'editorSuggestWidget.selectedBackground': '#434c5e',
      'extensionButton.prominentForeground': '#d8dee9',
      'extensionButton.prominentBackground': '#434c5e',
      'extensionButton.prominentHoverBackground': '#4c566a',
      errorForeground: '#bf616a',
      'debugExceptionWidget.background': '#4c566a',
      'debugExceptionWidget.border': '#2e3440',
      'debugToolBar.background': '#3b4252',
      'input.background': '#3b4252',
      'input.foreground': '#d8dee9',
      'input.placeholderForeground': '#d8dee999',
      'input.border': '#3b4252',
      'inputOption.activeBorder': '#88c0d0',
      'inputValidation.errorBackground': '#bf616a',
      'inputValidation.errorBorder': '#bf616a',
      'inputValidation.infoBackground': '#81a1c1',
      'inputValidation.infoBorder': '#81a1c1',
      'inputValidation.warningBackground': '#d08770',
      'inputValidation.warningBorder': '#d08770',
      'list.activeSelectionBackground': '#88c0d0',
      'list.activeSelectionForeground': '#2e3440',
      'list.inactiveSelectionBackground': '#434c5e',
      'list.inactiveSelectionForeground': '#d8dee9',
      'list.hoverForeground': '#eceff4',
      'list.focusForeground': '#d8dee9',
      'list.focusBackground': '#88c0d099',
      'list.hoverBackground': '#3b4252',
      'list.dropBackground': '#88c0d099',
      'list.highlightForeground': '#88c0d0',
      'list.errorForeground': '#bf616a',
      'list.warningForeground': '#ebcb8b',
      'merge.currentHeaderBackground': '#81a1c166',
      'merge.currentContentBackground': '#81a1c14d',
      'merge.incomingHeaderBackground': '#8fbcbb66',
      'merge.incomingContentBackground': '#8fbcbb4d',
      'merge.border': '#3b425200',
      'notification.background': '#3b4252',
      'notification.foreground': '#d8dee9',
      'notification.buttonBackground': '#434c5e',
      'notification.buttonHoverBackground': '#4c566a',
      'notification.buttonForeground': '#d8dee9',
      'notification.infoBackground': '#88c0d0',
      'notification.infoForeground': '#2e3440',
      'notification.warningBackground': '#ebcb8b',
      'notification.warningForeground': '#2e3440',
      'notification.errorBackground': '#bf616a',
      'notification.errorForeground': '#2e3440',
      'panel.background': '#2e3440',
      'panel.border': '#3b4252',
      'panelTitle.activeBorder': '#88c0d000',
      'panelTitle.activeForeground': '#88c0d0',
      'panelTitle.inactiveForeground': '#d8dee9',
      'peekView.border': '#4c566a',
      'peekViewEditor.background': '#2e3440',
      'peekViewEditorGutter.background': '#2e3440',
      'peekViewEditor.matchHighlightBackground': '#88c0d0cc',
      'peekViewResult.background': '#2e3440',
      'peekViewResult.fileForeground': '#88c0d0',
      'peekViewResult.lineForeground': '#d8dee966',
      'peekViewResult.matchHighlightBackground': '#88c0d0cc',
      'peekViewResult.selectionBackground': '#434c5e',
      'peekViewResult.selectionForeground': '#d8dee9',
      'peekViewTitle.background': '#3b4252',
      'peekViewTitleDescription.foreground': '#d8dee9',
      'peekViewTitleLabel.foreground': '#88c0d0',
      'pickerGroup.border': '#3b4252',
      'pickerGroup.foreground': '#d8dee9',
      'progressBar.background': '#88c0d0',
      'scrollbar.shadow': '#00000066',
      'scrollbarSlider.activeBackground': '#434c5eaa',
      'scrollbarSlider.background': '#434c5e99',
      'scrollbarSlider.hoverBackground': '#434c5eaa',
      'selection.background': '#88c0d099',
      'sideBar.background': '#2e3440',
      'sideBar.foreground': '#d8dee9',
      'sideBar.border': '#3b4252',
      'sideBarSectionHeader.background': '#3b4252',
      'sideBarSectionHeader.foreground': '#d8dee9',
      'sideBarTitle.foreground': '#d8dee9',
      'statusBar.background': '#3b4252',
      'statusBar.debuggingBackground': '#5e81ac',
      'statusBar.debuggingForeground': '#d8dee9',
      'statusBar.noFolderForeground': '#d8dee9',
      'statusBar.noFolderBackground': '#3b4252',
      'statusBar.foreground': '#d8dee9',
      'statusBarItem.activeBackground': '#4c566a',
      'statusBarItem.hoverBackground': '#434c5e',
      'statusBarItem.prominentBackground': '#3b4252',
      'statusBarItem.prominentHoverBackground': '#434c5e',
      'statusBar.border': '#3b425200',
      'tab.activeBackground': '#3b4252',
      'tab.activeForeground': '#d8dee9',
      'tab.border': '#3b425200',
      'tab.activeBorder': '#88c0d000',
      'tab.unfocusedActiveBorder': '#88c0d000',
      'tab.inactiveBackground': '#2e3440',
      'tab.inactiveForeground': '#d8dee966',
      'tab.unfocusedActiveForeground': '#d8dee999',
      'tab.unfocusedInactiveForeground': '#d8dee966',
      'tab.hoverBackground': '#3b4252cc',
      'tab.unfocusedHoverBackground': '#3b4252b3',
      'tab.hoverBorder': '#88c0d000',
      'tab.unfocusedHoverBorder': '#88c0d000',
      'terminal.background': '#2e3440',
      'terminal.foreground': '#d8dee9',
      'terminal.ansiBlack': '#3b4252',
      'terminal.ansiRed': '#bf616a',
      'terminal.ansiGreen': '#a3be8c',
      'terminal.ansiYellow': '#ebcb8b',
      'terminal.ansiBlue': '#81a1c1',
      'terminal.ansiMagenta': '#b48ead',
      'terminal.ansiCyan': '#88c0d0',
      'terminal.ansiWhite': '#e5e9f0',
      'terminal.ansiBrightBlack': '#4c566a',
      'terminal.ansiBrightRed': '#bf616a',
      'terminal.ansiBrightGreen': '#a3be8c',
      'terminal.ansiBrightYellow': '#ebcb8b',
      'terminal.ansiBrightBlue': '#81a1c1',
      'terminal.ansiBrightMagenta': '#b48ead',
      'terminal.ansiBrightCyan': '#8fbcbb',
      'terminal.ansiBrightWhite': '#eceff4',
      'titleBar.activeBackground': '#2e3440',
      'titleBar.activeForeground': '#d8dee9',
      'titleBar.border': '#2e344000',
      'titleBar.inactiveBackground': '#2e3440',
      'titleBar.inactiveForeground': '#d8dee966',
      'walkThrough.embeddedEditorBackground': '#2e3440',
      'welcomePage.buttonBackground': '#434c5e',
      'welcomePage.buttonHoverBackground': '#4c566a',
      'widget.shadow': '#00000066'
    }
  })
}

export default register
